workflows:
  ios-method-1:
    name: Rise Workflow
    environment:
      ios_signing:
        distribution_type: ad_hoc
        bundle_identifier: com.riseapp.riseng
    scripts:
      - script: keychain initialize
      - script: keychain add-certificate
      - script: xcode project use-profiles
      - script: flutter packages pub get
      - name: Flutter build ipa and automatic versioning
        script: /
          flutter build ipa --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - mobile@rise.ng
          - bolarinwabadejo@gmail.com
          - riseapp.ng@gmail.com
  ios-method-2:
    name: Rise Workflow 2
    environment:
      ios_signing:
        provisioning_profiles:
          - ProvProfile_rise
        certificates:
          - Distribute_Certificate
    scripts:
      - script: xcode project use-profiles
      - script: flutter packages pub get
      - name: Flutter build ipa and automatic versioning
        script: /
          flutter build ipa --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - mobile@rise.ng
          - bolarinwabadejo@gmail.com
          - riseapp.ng@gmail.comworkflows:
  ios-method-1:
    name: Rise Workflow
    environment:
      ios_signing:
        distribution_type: ad_hoc
        bundle_identifier: ng.rise.rise
    scripts:
      - script: keychain initialize
      - script: keychain add-certificate
      - script: xcode project use-profiles
      - script: flutter packages pub get
      - name: Flutter build ipa and automatic versioning
        script: /
          flutter build ipa --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - mobile@rise.ng
          - bolarinwabadejo@gmail.com
          - riseapp.ng@gmail.com
  ios-method-2:
    name: Rise Workflow 2
    environment:
      ios_signing:
        provisioning_profiles:
          - ProvProfile_rise
        certificates:
          - Distribute_Certificate
    scripts:
      - script: xcode project use-profiles
      - script: flutter packages pub get
      - name: Flutter build ipa and automatic versioning
        script: /
          flutter build ipa --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - mobile@rise.ng
          - bolarinwabadejo@gmail.com
          - riseapp.ng@gmail.com