workflows:
  ios-method-1:
    name: Rise Workflow
    environment:
      ios_signing:
        distribution_type: ad_hoc
        bundle_identifier: com.riseapp.riseng
    scripts:
      - script: keychain initialize
      - script: keychain add-certificate
      - script: xcode project use-profiles
      - script: flutter packages pub get
      - name: Flutter build ipa and automatic versioning
        script: /
          flutter build ipa --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - mobile.developer@rise.ng
          - bolarinwabadejo@gmail.com
          - riseapp.ng@gmail.com

  ios-method-2:
    name: Rise Workflow 2
    environment:
      groups:
        - app_store_credentials
      ios_signing:
        provisioning_profiles:
          - new_build_profile
        certificates:
          - New Build
    integrations: 
      app_store_connect: Olawunmi Oyedeji
    scripts:
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles
      - name: PUB GET
        script: flutter packages pub get
      - name: Flutter build ipa and automatic versioning
        script: /
          CURRENT_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number "$APP_STORE_ID")
          flutter build ipa --release --build-number=$(($CURRENT_BUILD_NUMBER + 1)) --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_app_store: true
      email:
        recipients:
          - mobile_developer@rise.ng
          - bolarinwabadejo@gmail.com
          - riseapp.ng@gmail.com