name: rise
description: Rise in Yoruba means to find work
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.2

environment:
  sdk: '>=2.18.3 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter




  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons:
  form_field_validator:
  flutter_svg:
  path_provider:
  multi_image_picker:
  image_picker:
  http:
  lecle_flutter_absolute_path:
  flutter_datetime_picker:
    git:
      url: https://github.com/Realank/flutter_datetime_picker.git
      ref: master
  modal_bottom_sheet: ^2.1.2
  permission_handler:
  flutter_native_image:
  shared_preferences:
  geolocator: ^8.2.0
  geocoding: ^2.0.4
  google_maps_widget:
  flutter_profile_picture: ^2.0.0
  flutter_easyloading:
  cached_network_image:
  flutter_google_places:
  url_launcher:
  firebase_core:
  firebase_auth:
  firebase_messaging:
  dio:
  liquid_pull_to_refresh: ^3.0.1
  change_app_package_name:
  google_fonts: ^4.0.3
  bottom_navy_bar:
  flutter_bloc:
  equatable:
  awesome_snackbar_content: ^0.1.0
  file_picker: ^5.2.5
  sizer:
  # flutter_google_places_sdk:
  swipe_refresh:
  intl:
  flutter_local_notifications:
  connectivity_plus: ^2.3.6+1
  webview_flutter: ^3.0.2
  flutter_share: ^2.0.0
  flutter_carousel_widget: ^2.0.2

dependency_overrides:
  modal_bottom_sheet:
    git:
      url: https://github.com/danReynolds/modal_bottom_sheet.git
      path: modal_bottom_sheet
  # flutter_identity_kyc: ^0.1.4
#  modal_bottom_sheet:
#    git:
#      url: https://github.com/danReynolds/modal_bottom_sheet.git
#      path: modal_bottom_sheet


dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  flutter_icons:


  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints:
  flutter_launcher_icons:
  flutter_native_splash:

flutter_icons:
  android: true
  ios: true
  web: true
  image_path: "assets/images/ic_launcher.png"
  image_path_ios: 'assets/images/ic_launcher.png'
  adaptive_icon_foreground: "#000000"

flutter_native_splash:
  color: '#ffffff'
  android: true
  ios: true
  web: true
  image: "assets/images/ic_launcher.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Chillax
      fonts:
        - asset: assets/fonts/Chillax-Bold.ttf
        - asset: assets/fonts/Chillax-Extralight.ttf
        - asset: assets/fonts/Chillax-Light.ttf
        - asset: assets/fonts/Chillax-Medium.ttf
        - asset: assets/fonts/Chillax-Regular.ttf
        - asset: assets/fonts/Chillax-Semibold.ttf
        - asset: assets/fonts/Chillax-Variable.ttf

    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    #
  assets:
    - assets/images/
    - assets/icons/
      # For details regarding fonts from package dependencies,
      # see https://flutter.dev/custom-fonts/#from-packages


