// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrnEOLJqTptSdtcvwroNy6uoQ3ujYhdkM',
    appId: '1:792388016740:android:2f89f9b4a3d70a4d75dd71',
    messagingSenderId: '792388016740',
    projectId: 'riseapp-90c83',
    storageBucket: 'riseapp-90c83.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaIo7Ak7L00NFtIA1wEtWAxmqqcb28acQ',
    appId: '1:792388016740:ios:415ef41579f9bff175dd71',
    messagingSenderId: '792388016740',
    projectId: 'riseapp-90c83',
    storageBucket: 'riseapp-90c83.appspot.com',
    androidClientId: '792388016740-5ecdd3gukpt1tcocn29v4tpcf1554m79.apps.googleusercontent.com',
    iosClientId: '792388016740-jf1kcr812ua4h07a15psfedp3ino1fs4.apps.googleusercontent.com',
    iosBundleId: 'com.israel.rise',
  );
}
